CREATE TABLE CLIENTE (
    ID BIGSERIAL PRIMARY KEY,
    CPF VARCHAR(11) UNIQUE,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTO (
    ID BIGSERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    PRECO NUMERIC(20, 2)
);

CREATE TABLE PEDIDO (
    ID BIGSERIAL PRIMARY KEY,
    CLIENTE_ID BIGSERIAL REFERENCES CLIENTE (ID),
    DATA_PEDIDO TIMESTAMP,
    STATUS VARCHAR(50),
    TOTAL NUMERIC(20, 2)
);

CREATE TABLE ITEM_PEDIDO (
    ID BIGSERIAL PRIMARY KEY,
    QUANTIDADE INTEGER,
    PEDIDO_ID BIGSERIAL REFERENCES PEDIDO (ID),
    PRODUTO_ID BIGSERIAL REFERENCES PRODUTO (ID)
);

CREATE TABLE USUARIO (
    ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ADMIN BOOL
);